### ISSUE TITLE
Game crashes when moving WH generators

### ISSUE THREAD

**Issue by Gloomyempire** [codeka/wwmmo#148]
When you try to move wormhole generators and click on a star too many times it will crash the game. This doesn't usually happen the first time buy if you click in open space and then click on a star it will crash the game. It makes setting up wormholes a little annoying at times especially if you want to get it at a good location where it will be as close as possible to a star that the wormhole is defending.

**Comment by codeka** [comment]
```
2018-11-16 16:35:24.928 20613-20976/au.com.codeka.warworlds.debug E/AndroidRuntime: FATAL EXCEPTION: UpdateThread
    Process: au.com.codeka.warworlds.debug, PID: 20613
    org.andengine.util.IDisposable$AlreadyDisposedException
        at org.andengine.entity.Entity.dispose(Entity.java:1449)
        at au.com.codeka.warworlds.game.starfield.StarEntity.dispose(StarEntity.java:109)
        at au.com.codeka.warworlds.game.starfield.StarfieldScene.disposeScene(StarfieldScene.java:299)
        at au.com.codeka.warworlds.game.starfield.SectorSceneManager$2$1.run(SectorSceneManager.java:153)
        at org.andengine.engine.handler.runnable.RunnableHandler.onUpdate(RunnableHandler.java:42)
        at org.andengine.engine.Engine.onUpdateUpdateHandlers(Engine.java:623)
        at org.andengine.engine.Engine.onUpdate(Engine.java:611)
        at org.andengine.engine.Engine.onTickUpdate(Engine.java:574)
        at org.andengine.engine.Engine$UpdateThread.run(Engine.java:870)

```
